### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by gzoller** [pjfanning/scala3-reflection#12]
Hello...

Leaving comment here, although I have done work over the weekend to pull in your changes to the main code base, so 1.1.11 should be up-to-date.  I may continue playing the deployment, as I'm not 100% sure its as smooth as it should be.

I do have a couple of questions.  I see you've added support for Zulu8 Java, presumable for Azure?  Is there support for a newer JDK?  That's JDK8 is very old and many enterprises don't like it due to the many unresolved security flaws in it.  I've been supported JDK13 in my work up to now.

I also see you've added some actions like actions/upload-artifact@v3.  What does this do, and why does it help?  I read the docs for this but still don't feel I understand why it's used.

Most of all--thank you very much for your help with the fixes!  Great stuff.  Sorry I've been busy at work a lot and missed the issues noted.

Cheers!
Greg

**Comment by pjfanning** [comment]
Thanks @gzoller for building and publishing a new jar.

With my fork, I use sbt-typelevel-sonatype-ci-release to generate the Github workflow files. Tagging a commit with a tag that starts with a 'v', eg `v1.2.0`, will lead to a release being made to Sonatype and ultimately, Maven Central.

I understand that JDK 8 is old but security patches are still released. I would recommend that all users use a e recent LTS like the latest version of JDK 17 but I'm happy to build and publish with JDK 8 - ensuring that the published jars can be used a wide range of JDKs.

**Comment by gzoller** [comment]
Makes sense.  Ok, I'll keep Zulu8 for the reasons given.
I'll also move to the 'v' thing for scala-reflection.  I had to modify my gitflow-packager product to get it to generate the correct artifact name (basically to drop the 'v'), but that was an easy fix.

**Comment by gzoller** [comment]
Almost forgot... what does the actions/upload-artifact@v3 do?

**Comment by pjfanning** [comment]
https://github.com/actions/upload-artifact is used to store artifacts so that other jobs can access them - the compile/test job is separate from the publish job.
